Release v0.8.1 version
flathub/io.github.Figma_Linux.figma_linux pull request #7
Opened 2021-07-24 00:54 UTC by ChugunovRoman

2021-07-24 13:34 UTC, jannuary requested changes
You have two closing </ul> tags in the appdata file. (line 41)

2021-07-24 13:35 UTC, jannuary commented on io.github.Figma_Linux.figma_linux.appdata.xml
> +          </ul>
Furthermore, you are not supposed to remove the older changelogs from appdata.

2021-07-25 04:17 UTC, jannuary approved these changes

2021-07-30 13:33 UTC, gasinvein commented
So, should this be merged (as asked in https://github.com/flathub/io.github.Figma_Linux.figma_linux/commit/e3a51bd76e9f3ad2677c781eff20c055fae700dd#r54139261)?

2021-07-30 20:20 UTC, ChugunovRoman commented
> So, should this be merged (as asked in [e3a51bd#r54139261](https://github.com/flathub/io.github.Figma_Linux.figma_linux/commit/e3a51bd76e9f3ad2677c781eff20c055fae700dd#r54139261))?

Yes, it's need to merge

2021-07-30 20:25 UTC, gasinvein commented
Oh wait, I don't see a merge button here either. Something isn't right.

@bilelmoussaoui @TingPing Any idea what's wrong here?

2021-07-30 22:47 UTC, merged

2021-07-30 22:49 UTC, nedrichards commented
@ChugunovRoman you need to accept the github invitation to have write access. I've sent it again.

2021-08-02 10:32 UTC, ChugunovRoman commented
> @ChugunovRoman you need to accept the github invitation to have write access. I've sent it again.

@nedrichards Hi, I accepted the github invitation, but I don't see the merge button still. I cannot merge https://github.com/flathub/io.github.Figma_Linux.figma_linux/pull/8

2021-08-02 13:56 UTC, gasinvein commented
@ChugunovRoman I don't see a "Collaborator" badge on your comments headers either. Weird.